services:
  backend:
    build: ./backend

    container_name: prompt-backend

    ports:
      - "8000:8000"

    environment:
      - PORT=8000
      - MONGO_URI=mongodb://mongodb:27017

    depends_on:
      - mongodb

    networks:
      - prompt-eval-network

  mongodb:
    image: mongo:latest

    container_name: mongodb

    ports:
      - "27017:27017"

    networks:
      - prompt-eval-network

  frontend:
    build: ./frontend

    container_name: prompt-frontend

    ports:
      - "3000:80"

    depends_on:
      - backend

    networks:
      - prompt-eval-network

  prometheus:
    image: prom/prometheus

    container_name: prometheus

    ports:
      - "9090:9090"

    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

    networks:
      - prompt-eval-network

  grafana:
    image: grafana/grafana

    container_name: grafana

    ports:
      - "3001:3000"

    depends_on:
      - prometheus

    networks:
      - prompt-eval-network

  sonarqube:
    image: sonarqube:lts-community

    container_name: sonarqube

    ports:
      - "9000:9000"

    networks:
      - prompt-eval-network

  jenkins:
    image: jenkins/jenkins:lts

    container_name: jenkins

    ports:
      - "8080:8080"
      - "50000:50000"

    volumes:
      - jenkins_home:/var/jenkins_home

    networks:
      - prompt-eval-network

networks:
  prompt-eval-network:
    driver: bridge

volumes:
  jenkins_home:
    external: true
